In [1]:
# Import libraries
import pandas as pd
import numpy as np

## First let's try with the rus dataset

In [2]:
train = pd.read_csv('train_rus.csv')
test = pd.read_csv('test_data.csv')

In [3]:
# Remove features we don't need for modeling
train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [4]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [5]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [6]:
train.shape

(50154, 141)

## Applying PCA

In [7]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.decomposition import PCA
pca = PCA(n_components = 50)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

## Logistic Regression

In [8]:
## Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [9]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30619    35]
 [ 8385     8]]


0.7843624350142137

## Random Forest

In [10]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [11]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30637    17]
 [ 8385     8]]


0.7848234179322355

## Decision Tree

In [12]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [13]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18335 12319]
 [ 4938  3455]]


0.5580454324275873

## Now let's try with the ros dataset

In [14]:
train = pd.read_csv('train_ros.csv')
test = pd.read_csv('test_data.csv')

In [15]:
# Remove features we don't need for modeling
train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [16]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [17]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [18]:
train.shape

(117729, 141)

## Applying PCA

In [19]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.decomposition import PCA
pca = PCA(n_components = 50)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

## Logistic Regression

In [20]:
## Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [21]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30646     8]
 [ 8392     1]]


0.7848746382564602

## Random Forest

In [22]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [23]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30653     1]
 [ 8393     0]]


0.7850282992291341

## Decision Tree

In [24]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [25]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[23614  7040]
 [ 6414  1979]]


0.6554408789407637