In [3]:
# Import libraries
import pandas as pd
import numpy as np

## First let's try with the rus dataset

In [4]:
train = pd.read_csv('train_rus.csv')
test = pd.read_csv('test_data.csv')

In [5]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [7]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [8]:
train.shape

(50154, 144)

## Applying PCA

In [10]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.decomposition import PCA
pca = PCA(n_components = 50)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

## Logistic Regression

In [11]:
## Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [12]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15552 15102]
 [ 4045  4348]]


0.5096422260352909

## Random Forest

In [13]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [14]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30633    21]
 [ 8387     6]]


0.7846697569595615

## Decision Tree

In [15]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [28]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18856 11798]
 [ 4863  3530]]


0.5733090890465337

## Now let's try with the ros dataset

In [17]:
train = pd.read_csv('train_ros.csv')
test = pd.read_csv('test_data.csv')

In [18]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [20]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [21]:
train.shape

(117729, 144)

## Applying PCA

In [22]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.decomposition import PCA
pca = PCA(n_components = 50)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

## Logistic Regression

In [23]:
## Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [24]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15544 15110]
 [ 4024  4369]]


0.5099751581427511

## Random Forest

In [25]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [26]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30652     2]
 [ 8393     0]]


0.7850026890670218

## Decision Tree

In [27]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [28]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[23792  6862]
 [ 6317  2076]]


0.6624836735216534