In [1]:
# Import libraries
import pandas as pd
import numpy as np

## First let's try with the rus dataset

In [2]:
# train = pd.read_csv('train_rus.csv')
# test = pd.read_csv('test_data.csv')

In [5]:
X_train = pd.read_csv('train_rus.csv')
X_test = pd.read_csv('test_data.csv')
y_train = pd.read_csv("y_train.csv")

In [6]:
# Remove features we don't need for modeling
X_train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
X_test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [4]:
# X_train = train.iloc[:, :-1].values
# y_train = train.iloc[:, -1].values

In [5]:
# X_test = test.iloc[:, :-1].values
# y_test = test.iloc[:, -1].values

In [9]:
train.shape

(50154, 141)

In [7]:
X_train

array([[ 0.        ,  0.        ,  0.        , ...,  0.48834986,
        -0.76923114, -0.6610703 ],
       [ 0.        ,  0.        ,  0.        , ..., -0.3700482 ,
        -1.14445363, -1.2662481 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.05915083,
        -0.74864932, -1.04816601],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.48834986,
         0.21236355,  0.08404351],
       [ 0.        ,  0.        ,  0.        , ...,  0.48834986,
        -0.54758073, -0.40664119],
       [ 0.        ,  0.        ,  0.        , ..., -0.58464771,
         0.3548531 ,  0.62924874]])

In [8]:
y_train

array([0, 0, 0, ..., 1, 1, 1])

## Applying LDA

In [11]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

ValueError: Unknown label type: (array([-0.6610703 , -1.2662481 , -1.04816601, ...,  0.08404351,
       -0.40664119,  0.62924874]),)

# Cross Validate

In [7]:
from sklearn.model_selection import cross_validate
def crossvalidation(model, X, y):
    scores = cross_validate(model, X, y, cv=3,
                         scoring=('roc_auc','accuracy','precision','recall'),
                         return_train_score=True)
    return scores

## Logistic Regression

#### Model #1: Baseline

In [10]:
## Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [11]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29968   686]
 [ 7799   594]]


0.7826977744769125

#### Model #2: Tuned

In [7]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0)
scores = crossvalidation(clf, X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


ValueError: Unknown label type: 'continuous'

In [8]:
y_train

array([-0.6610703 , -1.2662481 , -1.04816601, ...,  0.08404351,
       -0.40664119,  0.62924874])

In [12]:
import matplotlib.pyplot as plt

## Random Forest

In [14]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [15]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29704   950]
 [ 7746   647]]


0.7772940302712116

## Decision Tree

In [16]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [17]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18794 11860]
 [ 4961  3432]]


0.5692114631085615

## Now let's try with the ros dataset

In [22]:
train = pd.read_csv('train_ros.csv')
test = pd.read_csv('test_data.csv')

In [23]:
# Remove features we don't need for modeling
train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [24]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [25]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [26]:
train.shape

(117729, 141)

## Applying LDA

In [27]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

## Logistic Regression

In [28]:
## Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [29]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30020   634]
 [ 7816   577]]


0.7835941301508439

## Random Forest

In [31]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [32]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29978   676]
 [ 7833   560]]


0.7820831305862166

## Decision Tree

In [33]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [34]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24083  6571]
 [ 6448  1945]]


0.6665812994596256