In [53]:
# Import libraries
import pandas as pd
import numpy as np

## First let's try with the rus dataset

In [54]:
train = pd.read_csv('train_rus.csv')
test = pd.read_csv('test_data.csv')

In [55]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [56]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [57]:
train.shape

(50154, 144)

In [58]:
X_train

array([[ 2.05009000e+05,  1.88000000e+02,  0.00000000e+00, ...,
         4.88349862e-01, -7.69231143e-01, -6.61070299e-01],
       [ 2.77367000e+05,  2.40000000e+01,  0.00000000e+00, ...,
        -3.70048196e-01, -1.14445363e+00, -1.26624810e+00],
       [ 2.36619000e+05,  4.30000000e+01,  0.00000000e+00, ...,
         5.91508329e-02, -7.48649319e-01, -1.04816601e+00],
       ...,
       [ 2.78659000e+05,  5.80000000e+01,  0.00000000e+00, ...,
         4.88349862e-01,  2.12363546e-01,  8.40435113e-02],
       [ 2.61815000e+05,  1.10000000e+02,  0.00000000e+00, ...,
         4.88349862e-01, -5.47580729e-01, -4.06641193e-01],
       [ 2.22150000e+05,  7.00000000e+00,  0.00000000e+00, ...,
        -5.84647711e-01,  3.54853098e-01,  6.29248738e-01]])

In [59]:
y_train

array([0, 0, 0, ..., 1, 1, 1])

## Applying LDA

In [60]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

## Logistic Regression

In [61]:
## Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [62]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29948   706]
 [ 7788   605]]


0.7824672830179015

In [66]:
import matplotlib.pyplot as plt

In [67]:
## Visualizing the Training Set Results
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01))
plt.contourf(X1, classifier.predict(np.array([X1.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'blue')))
plt.xlim(X1.min(), X1.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'blue'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('LD1')
plt.ylabel('LD2')
plt.legend()
plt.show()

AttributeError: 'list' object has no attribute 'ravel'

## Random Forest

In [36]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [37]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29826   828]
 [ 7786   607]]


0.7793940635644223

## Decision Tree

In [38]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [39]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18695 11959]
 [ 5017  3376]]


0.5652418879811509

## Now let's try with the ros dataset

In [40]:
train = pd.read_csv('train_ros.csv')
test = pd.read_csv('test_data.csv')

In [41]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [42]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [43]:
train.shape

(117729, 144)

## Applying LDA

In [46]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

## Logistic Regression

In [47]:
## Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [48]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30647     7]
 [ 8393     0]]


0.7848746382564602

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green', 'blue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('LD1')
plt.ylabel('LD2')
plt.legend()
plt.show()

## Random Forest

In [49]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [50]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30590    64]
 [ 8373    20]]


0.7839270622583041

## Decision Tree

In [51]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [52]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[23945  6709]
 [ 6571  1822]]


0.6598970471483084