In [1]:
# Import libraries
import pandas as pd
import numpy as np

## First let's try with the rus dataset

In [2]:
# train = pd.read_csv('train_rus.csv')
# test = pd.read_csv('test_data.csv')

In [2]:
X_train = pd.read_csv('train_rus.csv')
X_test = pd.read_csv('test_data.csv')
y_train = pd.read_csv("y_train.csv")
y_test = pd.read_csv('y_test.csv')

In [3]:
# Remove features we don't need for modeling
X_train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
X_test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [4]:
# X_train = train.iloc[:, :-1].values
# y_train = train.iloc[:, -1].values

In [5]:
# X_test = test.iloc[:, :-1].values
# y_test = test.iloc[:, -1].values

In [9]:
train.shape

(50154, 141)

In [7]:
X_train

array([[ 0.        ,  0.        ,  0.        , ...,  0.48834986,
        -0.76923114, -0.6610703 ],
       [ 0.        ,  0.        ,  0.        , ..., -0.3700482 ,
        -1.14445363, -1.2662481 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.05915083,
        -0.74864932, -1.04816601],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.48834986,
         0.21236355,  0.08404351],
       [ 0.        ,  0.        ,  0.        , ...,  0.48834986,
        -0.54758073, -0.40664119],
       [ 0.        ,  0.        ,  0.        , ..., -0.58464771,
         0.3548531 ,  0.62924874]])

In [8]:
y_train

array([0, 0, 0, ..., 1, 1, 1])

# Interaction 

In [38]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(interaction_only=True,include_bias = False)
poly.fit(X_train)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)

In [41]:
X_train = pd.DataFrame(poly.transform(X_train),columns=poly.get_feature_names(X_train.columns))
X_test = pd.DataFrame(poly.transform(X_test),columns=poly.get_feature_names(X_test.columns))

## VIF

In [7]:
from statsmodels.stats.outliers_influence import variance_inflation_factor 
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X_train.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X_train.values, i) 
                          for i in range(len(X_train.columns))] 
  

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1543: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:181: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)


In [8]:
vif_data.sort_values('VIF',ascending=False)

feature       VIF
46                          icu_stay_type_admit       inf
35              hospital_admit_source_Other.ICU       inf
26           hospital_admit_source_Direct.Admit       inf
27   hospital_admit_source_Emergency.Department       inf
28                  hospital_admit_source_Floor       inf
29                    hospital_admit_source_ICU       inf
30             hospital_admit_source_ICU.to.SDU       inf
31            hospital_admit_source_Observation       inf
32         hospital_admit_source_Operating.Room       inf
33                  hospital_admit_source_Other       inf
34         hospital_admit_source_Other.Hospital       inf
36                   hospital_admit_source_PACU       inf
47                        icu_stay_type_readmit       inf
37          hospital_admit_source_Recovery.Room       inf
38   hospital_admit_source_Step.Down.Unit..SDU.       inf
39                hospital_admit_source_Unknown       inf
40        icu_admit_source_Accident...Emergency       inf
41                       icu_admit_source_Floor       inf
42   icu_admit_source_Operating.Room...Recovery       inf
43              icu_admit_source_Other.Hospital       inf
44                   icu_admit_source_Other.ICU       inf
45                     icu_admit_source_Unknown       inf
25      hospital_admit_source_Chest.Pain.Center       inf
24       hospital_admit_source_Acute.Care.Floor       inf
23                               gender_Unknown       inf
49                           icu_type_CCU.CTICU       inf
56                                icu_type_SICU       inf
55                           icu_type_Neuro.ICU       inf
54                        icu_type_Med.Surg.ICU       inf
53                                icu_type_MICU       inf
..                                          ...       ...
135                            d1_potassium_min  2.675633
108                             h1_resprate_max  2.315174
83                             d1_heartrate_min  2.232559
109                             h1_resprate_min  2.155844
88                              d1_resprate_max  2.090500
73                              resprate_apache  2.012519
111                                 h1_spo2_min  1.792495
72                                   map_apache  1.664438
110                                 h1_spo2_max  1.658336
89                              d1_resprate_min  1.656736
6                             ventilated_apache  1.623949
5                              intubated_apache  1.622282
96                                  d1_temp_max  1.605452
91                                  d1_spo2_min  1.516934
125                              d1_glucose_min  1.451103
8                                     cirrhosis  1.420742
9                               hepatic_failure  1.419974
57                                          age  1.408332
90                                  d1_spo2_max  1.357819
62                           apache_2_diagnosis  1.281082
60                             pre_icu_los_days  1.220486
10                            immunosuppression  1.123068
13                  solid_tumor_with_metastasis  1.091630
76                           urineoutput_apache  1.063469
4                             gcs_unable_apache  1.030518
11                                     leukemia  1.022168
12                                     lymphoma  1.015297
3                                    arf_apache  1.004426
7                                          aids  1.002369
1                            readmission_status       NaN

[140 rows x 2 columns]

In [9]:
vif_data = vif_data[vif_data['VIF'] <= 5] 

In [12]:
X_train = X_train.loc[:,vif_data['feature']]

In [13]:
X_test = X_test.loc[:,vif_data['feature']]

In [14]:
X_train.head()

arf_apache  gcs_unable_apache  intubated_apache  ventilated_apache  aids  \
0         0.0                0.0               0.0                0.0   0.0   
1         0.0                0.0               0.0                0.0   0.0   
2         0.0                0.0               0.0                0.0   0.0   
3         0.0                0.0               0.0                0.0   0.0   
4         0.0                0.0               0.0                0.0   0.0   

   cirrhosis  hepatic_failure  immunosuppression  leukemia  lymphoma  ...  \
0        0.0              0.0                0.0       0.0       0.0  ...   
1        0.0              0.0                0.0       0.0       0.0  ...   
2        0.0              0.0                0.0       0.0       0.0  ...   
3        0.0              0.0                0.0       0.0       0.0  ...   
4        0.0              0.0                0.0       0.0       0.0  ...   

   h1_spo2_max  h1_spo2_min  h1_temp_max  h1_temp_min  d1_calcium_max  \
0    -0.042665    -1.916890    -0.026301     0.092688        1.910814   
1    -0.042665    -1.448141    -0.026301     0.092688       -0.120731   
2     0.278880    -0.041895     0.240016     0.351113        0.024380   
3     0.278880     0.114354     0.565515     0.666966        0.024380   
4     0.278880     0.114354    -0.026301     0.092688        1.475483   

   d1_glucose_min  d1_hco3_max  d1_hco3_min  d1_potassium_max  \
0       -0.244492     2.144635     2.142633         -1.024551   
1       -0.731711     0.649091     0.181229         -0.074440   
2       -0.515169     0.150577     0.399163          0.875671   
3       -0.379830     0.150577    -0.036705         -0.232792   
4       -0.461034    -1.594225    -1.126374          1.667431   

   d1_potassium_min  
0         -0.592150  
1         -0.228522  
2         -0.228522  
3         -0.228522  
4          2.498686  

[5 rows x 43 columns]

# Grid Search

In [6]:
from sklearn.model_selection import GridSearchCV
def grid_search(params, model, x_train, y_train):
    gs = GridSearchCV(model, parameters)
    gs.fit(x_train, y_train)
    return gs

## Logistic Regression

#### Model #1: Baseline

In [10]:
## Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [11]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29968   686]
 [ 7799   594]]


0.7826977744769125

#### Model #2: Tuned

In [7]:
from sklearn.linear_model import LogisticRegression
parameters = {'penalty':['l1', 'l2'],'C':[1,2]}
clf = LogisticRegression(random_state=0)
scores = grid_search(parameters, clf, X_train, y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\skl

In [8]:
scores.cv_results_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\util

{'mean_fit_time': array([15.4383812 ,  9.45395509, 14.66234334,  9.76237869]),
 'std_fit_time': array([4.61322945, 0.95520527, 2.82322516, 0.93108643]),
 'mean_score_time': array([0.05857269, 0.01531339, 0.01434127, 0.01431735]),
 'std_score_time': array([0.06523715, 0.00186843, 0.00095488, 0.0004607 ]),
 'param_C': masked_array(data=[1, 1, 2, 2],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_penalty': masked_array(data=['l1', 'l2', 'l1', 'l2'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'penalty': 'l1'},
  {'C': 1, 'penalty': 'l2'},
  {'C': 2, 'penalty': 'l1'},
  {'C': 2, 'penalty': 'l2'}],
 'split0_test_score': array([0.61825577, 0.6183754 , 0.61831559, 0.61831559]),
 'split1_test_score': array([0.61729872, 0.6172389 , 0.61717909, 0.61717909]),
 'split2_test_score': array([0.61693983, 0.61711927, 0.61693983, 0.61699964]),
 'mean_test_score': ar

In [9]:
clf = LogisticRegression(**scores.best_params_)
clf.fit(X_train, y_train)

## Making the Confusion Matrix
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: X has 141 features per sample; expecting 140

## Random Forest

In [14]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [15]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29704   950]
 [ 7746   647]]


0.7772940302712116

#### Tuned

In [ ]:
from sklearn.ensemble import RandomForestClassifier

parameters = {'n_estimators':[100,200,300], 
              'criterion':['gini','entropy'],
              'max_features':['sqrt','log2']
             }
classifier = RandomForestClassifier()
scores = grid_search(parameters, classifier, X_train, y_train)


In [ ]:
scores.cv_results_

In [ ]:
classifier = RandomForestClassifier(**scores.best_params_)
classifier.fit(X_train,y_train)

In [ ]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from matplotlib import pyplot

y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


In [ ]:

# calculate roc curve
# keep probabilities for the positive outcome only
# predict probabilities
ns_probs = [0 for _ in range(len(y_test))]
lr_probs = classifier.predict_proba(X_test)
lr_probs = lr_probs[:, 1]
# calculate scores
ns_auc = roc_auc_score(y_test, ns_probs)
lr_auc = roc_auc_score(y_test, lr_probs)
# summarize scores
print('No Skill: ROC AUC=%.3f' % (ns_auc))
print('Logistic: ROC AUC=%.3f' % (lr_auc))
# calculate roc curves
ns_fpr, ns_tpr, _ = roc_curve(y_test, ns_probs)
lr_fpr, lr_tpr, _ = roc_curve(y_test, lr_probs)
# plot the roc curve for the model
pyplot.plot(ns_fpr, ns_tpr, linestyle='--', label='No Skill')
pyplot.plot(lr_fpr, lr_tpr, marker='.', label='Random Forest')
# axis labels
pyplot.xlabel('False Positive Rate')
pyplot.ylabel('True Positive Rate')
# show the legend
pyplot.legend()
# show the plot
pyplot.show()

## Decision Tree

In [16]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [17]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18794 11860]
 [ 4961  3432]]


0.5692114631085615

## Now let's try with the ros dataset

In [22]:
train = pd.read_csv('train_ros.csv')
test = pd.read_csv('test_data.csv')

In [23]:
# Remove features we don't need for modeling
train.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)
test.drop(['encounter_id', 'hospital_id', 'icu_id'], axis=1, inplace=True)

In [24]:
X_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [25]:
X_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [26]:
train.shape

(117729, 141)

## Applying LDA

In [27]:
# n_components = the final number of extracted features you want to end up with in your dataset
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

## Logistic Regression

In [28]:
## Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [29]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[30020   634]
 [ 7816   577]]


0.7835941301508439

## Random Forest

In [31]:
## Training the Random Forest Classifier on the Traininig Set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=10, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [32]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[29978   676]
 [ 7833   560]]


0.7820831305862166

## Decision Tree

In [33]:
## Training the Decision Tree on the Training Set
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)

In [34]:
## Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[24083  6571]
 [ 6448  1945]]


0.6665812994596256